### ISSUE TITLE
Training with my own dataset

### ISSUE THREAD

**Issue by bensuucar** [ychfan/tf_estimator_barebone#4]
Hi,

I would like to train EDSR/WDSR with my own training data from scratch.  However I am facing with this issue which I couldnt find any solution for.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected size[0] in [0, 108], but got 144
         [[Node: Slice_1 = Slice[Index=DT_INT32, T=DT_UINT8, _class=["loc:@cond/Switch_2"], _device="/device:CPU:0"](arg1, Slice_1/begin, Slice_1/size)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[16,48,48,3], [16,144,144,3]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

![capture](https://user-images.githubusercontent.com/34005410/48476798-e7669c00-e7f7-11e8-87ab-c640b2072a29.PNG)

Could you please help?

**Comment by ychfan** [comment]
Could you share more details about your code?
I guess the problem is from func `list_files`. It may caused by the lr and hr image filenames are not aligned. But I am not sure how you implement the `input_fn`
