### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by suke27** [ychfan/tf_estimator_barebone#6]
Hello, when I try to run
it prints:
AttributeError: 'Conv2DWeightNorm' object has no attribute 'add_weight'
could you help to check it, thank you!

**Comment by ychfan** [comment]
May I know your TF version? It should be right on 1.11 and 1.12.

**Comment by suke27** [comment]
my version is tf 1.6

**Comment by ychfan** [comment]
Please update to later versions.
